////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;

namespace NosTale.Packets.Packets.ClientPackets
{
    [PacketHeader("snap")]
    public class SnapPacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}