////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;

namespace NosTale.Packets.Packets.ClientPackets
{
    [PacketHeader("ob_a")]
    public class UseIconFalconSkillPacket : PacketDefinition
    {
        #region Properties        
        
        #endregion
    }
}