////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$Backpack", PassNonParseablePacket = true, Authority = AuthorityType.Administrator)]
    public class BackpackPacket : PacketDefinition
    {
        #region Methods

        public static string ReturnHelp() => "$Backpack";

        #endregion
    }
}