////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$ChangeSex", "$Sex" , PassNonParseablePacket = true, Authority = AuthorityType.SGM)]
    public class ChangeSexPacket : PacketDefinition
    {
        public static string ReturnHelp() => "$ChangeSex | $Sex";
    }
}