////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$SPLvl", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class ChangeSpecialistLevelPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte SpecialistLevel { get; set; }

        public static string ReturnHelp() => "$SPLvl <Value>";

        #endregion
    }
}