//// <auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$Event", PassNonParseablePacket = true, Authority = AuthorityType.CommunityManager)]
    public class EventPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public EventType EventType { get; set; }

        [PacketIndex(1)]
        public int LvlBracket { get; set; }

        public static string ReturnHelp() => "$Event <Event> <LevelBracket>";

        #endregion
    }
}