////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    //Homepacket
    [PacketHeader("$home", PassNonParseablePacket = true, Authority = AuthorityType.User)]
    public class HomePacket : PacketDefinition
    {
        #region Properties

        public static string ReturnHelp() => "$nosville";

        #endregion
    }
}