////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$Invisible" , PassNonParseablePacket = true, Authority = AuthorityType.GameSage)] //kentao.
    public class InvisiblePacket : PacketDefinition
    {
        public static string ReturnHelp() => "$Invisible";
    }
}