////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    //jobxppacket
    [PacketHeader("$jobxp", PassNonParseablePacket = true, Authority = AuthorityType.User)]
    public class JOBXPPacket : PacketDefinition
    {
        #region Properties

        public static string ReturnHelp() => "$jobxp";

        #endregion
    }
}