////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$krem", PassNonParseablePacket = true, Authority = AuthorityType.Administrator)]
    public class kremPacket : PacketDefinition
    {
        #region Properties

        public static string ReturnHelp() => "$nosville";

        #endregion
    }
}