////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$LeaveAct4", PassNonParseablePacket = true, Authority = AuthorityType.Administrator)]
    public class LeaveAct4Packet : PacketDefinition
    {
        #region Properties
        
        public static string ReturnHelp() => "$LeaveAct4";

        #endregion
    }
}