////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$MapPVP" , PassNonParseablePacket = true, Authority = AuthorityType.SGM)]
    public class MapPVPPacket : PacketDefinition
    {
        public static string ReturnHelp() => "$MapPVP";
    }
}