////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$ResetMap" , PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class MapResetPacket : PacketDefinition
    {
        #region Properties

        public static string ReturnHelp() => "$ResetMap";

        #endregion
    }
}