////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$MonsterInfo", PassNonParseablePacket = true, Authority = AuthorityType.Administrator)]
    public class MonsterInfoPacket : PacketDefinition
    {
        public static string ReturnHelp() => "$MonsterInfo";
    }
}