////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$Music", PassNonParseablePacket = true, Authorities = new AuthorityType[] { AuthorityType.Administrator })]
    public class MusicPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public int Music { get; set; }

        public static string ReturnHelp() => "$Music BGM";

        #endregion
    }
}