////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    //raidmappacket
    [PacketHeader("$raidmap", PassNonParseablePacket = true, Authority = AuthorityType.User)]
    public class RaidMapPacket : PacketDefinition
    {
        #region Properties

        public static string ReturnHelp() => "$raidmap";

        #endregion
    }
}