////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$SPRefill", PassNonParseablePacket = true, Authority = AuthorityType.Administrator)]
    public class SPRefillPacket : PacketDefinition
    {
        public static string ReturnHelp() => "$SPRefill";
    }
}