////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$Stat", PassNonParseablePacket = true, Authority = AuthorityType.Administrator)]
    public class StatCommandPacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}