////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$TeleportToMe", PassNonParseablePacket = true, Authority = AuthorityType.GameSage)] //kentao.
    public class SummonPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string CharacterName { get; set; }

        public static string ReturnHelp() => "$TeleportToMe <Nickname|*>";

        #endregion
    }
}