////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    //xppacket
    [PacketHeader("$xp", PassNonParseablePacket = true, Authority = AuthorityType.User)]
    public class XPPacket : PacketDefinition
    {
        #region Properties

        public static string ReturnHelp() => "$xp";

        #endregion
    }
}